# Generated by Django 5.0.6 on 2024-12-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('cat', models.IntegerField()),
                ('pdetails', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
