# Generated by Django 5.0.6 on 2025-01-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
